//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILDIRIM_KIMYASALLARI
    {
        public int BILDIRIM_KIMYASAL_ID { get; set; }
        public int FK_KIMYASAL_ID { get; set; }
        public int FK_BILDIRIM_ID { get; set; }
        public decimal ADLANDIRILMIS_INDEKSI_ALT { get; set; }
        public decimal ADLANDIRILMIS_INDEKSI_UST { get; set; }
        public decimal TOKSISITE_INDEKSI_ALT { get; set; }
        public decimal TOKSISITE_INDEKSI_UST { get; set; }
        public decimal ALEVLENIRLIK_INDEKSI_ALT { get; set; }
        public decimal ALEVLENIRLIK_INDEKSI_UST { get; set; }
        public decimal EKOTOKSISITE_INDEKSI_ALT { get; set; }
        public decimal EKOTOKSISITE_INDEKSI_UST { get; set; }
        public decimal MIKTAR { get; set; }
        public Nullable<decimal> KONSANTRASYON { get; set; }
        public string MUSTAHZAR_NOTLARI { get; set; }
        public string KARISIM_BILGILERI { get; set; }
    
        public virtual BILDIRIM BILDIRIM { get; set; }
        public virtual KIMYASAL KIMYASAL { get; set; }
    }
}
