//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Master { get; set; }
        public Nullable<int> CharacterLevel { get; set; }
        public string ClassCharType { get; set; }
    }
}
