//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEVESOIIEntities : DbContext
    {
        public SEVESOIIEntities()
            : base("name=SEVESOIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILDIRIM> BILDIRIM { get; set; }
        public virtual DbSet<BILDIRIM_KIMYASALLARI> BILDIRIM_KIMYASALLARI { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<KIMYASAL> KIMYASAL { get; set; }
        public virtual DbSet<RISK_BILGILERI> RISK_BILGILERI { get; set; }
        public virtual DbSet<SANAYICI> SANAYICI { get; set; }
        public virtual DbSet<SINIFLANDIRMA> SINIFLANDIRMA { get; set; }
    }
}
