//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_BILGILERI
    {
        public int RISK_BILGILERI_ID { get; set; }
        public string RISK_IBARESI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
